# Generated by Django 3.0.6 on 2020-05-24 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
                ('cijena', models.FloatField()),
                ('opis', models.CharField(max_length=256)),
                ('slika', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recenzija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocjena', models.IntegerField(null=True)),
                ('komentar', models.CharField(max_length=500)),
                ('artikl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshopapp.Artikl')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kosarica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukupnaCijena', models.FloatField()),
                ('artikli', models.ManyToManyField(to='bookshopapp.Artikl')),
            ],
        ),
        migrations.AddField(
            model_name='artikl',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshopapp.Autor'),
        ),
        migrations.AddField(
            model_name='artikl',
            name='zanr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshopapp.Zanr'),
        ),
    ]
