# Generated by Django 3.0.6 on 2020-06-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshopapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='prezime',
        ),
    ]
